### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by jaykijay** [BaxterStockman/ansible-connection-machinectl#4]
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 519, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/usr/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 788, in _get_connection
    connection = self._shared_loader_obj.connection_loader.get(conn_type, self._play_context, self._new_stdin, ansible_playbook_pid=to_text(os.getppid()))                                                                                                                                                      
  File "/usr/lib/python3.6/site-packages/ansible/plugins/loader.py", line 385, in get
    obj = obj(*args, **kwargs)
  File "/usr/share/ansible/plugins/connection/machinectl.py", line 204, in __init__
    self.machinectl = MachineCtl(kwargs.get('machinectl_command'))
  File "/usr/share/ansible/plugins/connection/machinectl.py", line 75, in __init__
    self.version = self._version()
  File "/usr/share/ansible/plugins/connection/machinectl.py", line 91, in _version
    matched = re.match(r'\Asystemd\s+(\d+)\D', version_output)
  File "/usr/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by tomeon** [comment]
Thanks for your issue report, @jaykijay -- will dig in this weekend.

**Comment by tomeon** [comment]
@jaykijay -- beg your pardon for the extremely long delay in addressing this issue.  Just a heads-up that I have not forgotten about this. I've been working on a fix over in the [python3-compat branch](/tomeon/ansible-connection-machinectl/tree/python3-compat); got passing results from Travis recently, and just need to do some cleanup work before merging.

**Comment by tomeon** [comment]
@jaykijay -- I've merged the fix(es) for the issue you encountered into master.  Would be much obliged if you could take a look.
